### PR TITLE
#693: Setup file not working on Mac

### PR DESCRIPTION
**Pull request by blizzarac**
Tested on mac

1. ide alias is not working like this -> Changing alias from source to ide to directly to ide
2. IDE_URL was missing -> Added for current folder

### CODE REVIEW

**Comment by hohwille** [comment]
@blizzarac thanks for testing IDEasy (in beta phase already) and trying to help by creating a PR 👍 
Could you please first describe the error you were experiencing on MacOS?
It is definitely wrong to remove the `source` statement from the script.
I can explain that in detail why we need to source the script (see also #63) but first I would like to understand what was going wrong.

> IDE_URL was missing -> Added for current folder

That is definitely a known issue for Linux and Mac you we were already thinking about fixing this in the way you did.
However, currently we have a OS specific solution for that on Windows setting this in the Windows System Environment Variables after calling the setup Bash script (see https://github.com/devonfw/IDEasy/blob/main/cli/src/main/package/setup.bat). Therefore we should add an OS check and avoid doing that on Windows.
```
if [ "${OSTYPE}" = "cygwin" ] || [ "${OSTYPE}" = "msys" ]; then
...
else
...
fi
```
Do you want to do that and update your PR? Otherwise, we are happy to take over your work and create a new PR fixing that and hopefully include that into the planned 2024.10.001-beta release.

**Comment by hohwille** [comment]
See also #423

**Comment by hohwille** [comment]
@blizzarac as you seem to be quite busy with other stuff, I would suggest the following:
* we create another PR for adding `IDE_ROOT` during setup for Linux and MacOS.
* you only need to provide a small explanation of the error that you were facing that lead you to removing the `source` instruction. If there is some other "bug" than the missing IDE_ROOT, we can fix that. A comment would even be sufficient if you have no time. Otherwise creating a new bug would be even better.

**Comment by blizzarac** [comment]
@hohwille sorry about, was a busy week. I think the problems that I had, had to do with my chaotic setup before I talked to @jan-vcapgemini and found out that I had to put everything in a _ide folder. Maybe this is the bug here (this was missing in the documentation)

**Comment by blizzarac** [comment]
I have pushed a new version removing the source parts and added the IDE_ROOT with OS guards, hope that works for you

**Review by hohwille — APPROVED** [review]
@blizzarac thank you so much for the update of your PR. This is now perfect and ready for merge 👍

**Pull request merged**
