### PR TITLE
#146 Implement automated coverage tools

### LINKED ISSUE #146: Implement automated coverage tools
To better check the test coverage of the project and improve the test quality and quantity a tool should be implemented to automatically check the coverage level.
 Tool in question are:

- [Jacoco](https://www.eclemma.org/jacoco/#:~:text=JaCoCo%20is%20a%20free%20code,existing%20libraries%20for%20many%20years.)
- [Coveralls](https://coveralls.io/)

### PR DESCRIPTION
**Pull request by moritzLanger**
closes #146 implement automated coverage tool

Jacoco has been added 

Coverall has been added to the GitHub workflow, to be used in PRs
Some Steps are needed to activate Coverall:

- [x] 1. Sign up to Coveralls.io on their website using the Repo owner
- [x] 2.  On the Coverall website navigate to settings and Activate "leave comments?" and set them to detailed, bevor saving the changes. (Once signed up the link to the settings will be https://coveralls.io/github/devonfw/IDEasy/settings )
- [x] 3. The coverall bot needs to be added to the repo, with write permissions (https://github.com/coveralls)

(Documentation can also be found on the Coveralls [docu page ](https://docs.coveralls.io/app-notifications#pull-request-comments))

### CODE REVIEW

**Comment by moritzLanger** [comment]
I was able to skip step 1. and complete step 2. (as I was allowed to change settings in coverall for defonfw/ideasy)

**Comment by MattesMrzik** [comment]
>... and complete step 2. (as I was allowed to change settings in coverall for defonfw/ideasy)

I think this setting can be changed by anyone on the web. Can we restrict this?

**Comment by moritzLanger** [comment]
> > ... and complete step 2. (as I was allowed to change settings in coverall for defonfw/ideasy)
> 
> I think this setting can be changed by anyone on the web. Can we restrict this?

The settings can be changed by anyone within the Devonfw Github Group, but i can look into restricting it further

**Review by MattesMrzik — COMMENTED** [review]
Looks good.

**Review by hohwille — APPROVED** [review]
@moritzLanger Thanks for creating the PR. Looks all great. 👍 
Also you used the latest version of the plugin what is always a best-practice
https://repo1.maven.org/maven2/org/jacoco/jacoco-maven-plugin/

**Comment by hohwille** [comment]
For the record: I did not grant "Write permissions" to `coveralls` as reading the documentation I found out that read access is sufficient. We will see if all works out or not.

**Comment by hohwille** [comment]
one last thing @moritzLanger
IMHO you forgot to add the badge for coveralls to our README in this PR.
Can you afterwards create a new PR for that.

**Comment by hohwille** [comment]
> one last thing @moritzLanger IMHO you forgot to add the badge for coveralls to our README in this PR. Can you afterwards create a new PR for that.

I just did it myself. Done.

**Pull request merged**
