### PR TITLE
#764: IDEasy not working properly in CMD

### PR DESCRIPTION
**Pull request by KianRolf**
Fixes: https://github.com/devonfw/IDEasy/issues/764

Changes the start script from bash to batch to enable ide intellij/tomcat/android-studio to be performed in the cmd

### CODE REVIEW

**Comment by jan-vcapgemini** [comment]
@KianRolf, thanks for your adjustment to use batch files instead of bash files. Please add a check for OS e.g. linux, mac, as these still need to use the bash file. We need to enforce that only on a windows machine, these batch files get created/used.
Please check this: https://github.com/devonfw/IDEasy/blob/d706ab4b077ecca19d98872f6d97c16ce315d3c5/cli/src/test/java/com/devonfw/tools/ide/tool/dotnet/DotNetTest.java#L59 it might come in handy.

**Comment by KianRolf** [comment]
The batch file now gets created additionally if the OS is windows. IDEasy automatically executes the correct file corresponding to the OS.

**Review by hohwille — APPROVED** [review]
@KianRolf thanks for your PR and your nice solution/workaround. This is great and I hope tests will confirm it fixes our bug 👍 
For the record I am not so sure if `start` vs. `call` should be used to run the binary from the `*.bat` script and also on Windows there are no executable permissions so `makeExecutable` will be a NO-OP on windows and could be omitted.
However, nothing wrong so I merge as is and we see how it will react.

**Comment by hohwille** [comment]
needs to be reverted - see #814, etc.

**Pull request merged**
