### PR TITLE
#183: removed isInstalledVersion()

### LINKED ISSUE #183: Duplicate message if tool is already installed
### Expected behavior

When installing a tool that is already installed I want to get a single message.

### Actual behavior

I get (for example):
```
Version v3.11.1 of tool helm is already installed at C:\projects\_ide\software\default\helm\helm\v3.11.1
Version v3.11.1 of tool helm is already installed
``` 

### Steps to reproduce 

Run `ide install <tool>` twice

### PR DESCRIPTION
**Pull request by MattesMrzik**
Fixes #183.  `isInstalledVersion()` was only used once and caused the duplicate msg if the tool was already installed.

### CODE REVIEW

**Review by hohwille — CHANGES_REQUESTED** [review]
Indeed we have this log message duplicated:
* https://github.com/devonfw/IDEasy/blob/f75bfa6e38ae77ba02238703754dae974e86cca2/cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java#L136
* https://github.com/devonfw/IDEasy/blob/f75bfa6e38ae77ba02238703754dae974e86cca2/cli/src/main/java/com/devonfw/tools/ide/tool/GlobalToolCommandlet.java#L45
* https://github.com/devonfw/IDEasy/blob/f75bfa6e38ae77ba02238703754dae974e86cca2/cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java#L178

So thanks @MattesMrzik for noticing and taking action to improve. 👍 
However, using the `silent` flag to determine the log-level is an intended behavior we have taken from `devonfw-ide`.
The idea is as following:
```
$ devon mvn setup
Version 3.9.6 of tool mvn is already installed
```
This is the intended default behavior. But also consider this:
```
$ devon --debug mvn setup
Version 17.0.8 of tool java is already installed
Version 3.9.6 of tool mvn is already installed
```
By default the user would not expect to get this info about java and that would come every time we run `mvn` if we log it statically on `info` or it would come never by default if we log statically on `debug` so `devon java setup` would give no feedback at all by default what would be confusing:
```
$ devon java setup
$
```
Your change is fine, but you should also add the dynamic logging part from `isInstalledVersion` method to `ToolCommandlet` as a protected method that is used by Local/GlobalToolCommandlet. I missed this on the review of #113 

UPDATE: I just see that in GlobalToolCommandlet we do not have a `version` so you could still do what I suggested but allow `GlobalToolCommandlet` to pass `null` as version parameter and log accordingly.

**Review by salimbouch — COMMENTED** [review]
Just like @hohwille said we need this dynamic logging otherwise we don't get any output when not in debugger mode. If I'm not mistaken you can move isInstalledVersion to ToolCommandlet and use it both in Global and Local, maybe call it isInstalled since Global Tools don't have any version.

**Review by salimbouch — APPROVED** [review]
Looks good to me 👍

**Review by hohwille — APPROVED** [review]
OK, PR does not avoid the redundancies but functionally now correct and ready for merge.
I commented on #52 because of the pointless line-wrapping changes, but this can now be merged. Thanks again 👍

**Pull request merged**
